name: pal
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.0.0
  #process_run: ^0.12.2
  #vector_math: ^2.1.4
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.1
  #usb_serial: ^0.2.5
  permission_handler: ^10.4.0
  #flutter_nearby_connections: ^1.0.0
  #file_picker: ^5.2.3
  tapsell_plus: ^2.3.2
  #shared_preferences: ^2.2.2
  #device_info_plus: ^10.1.0
  #path_provider: ^2.0.0
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
